#!/bin/sh
# PROVIDE: centralssh
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="centralssh"
rcvar="${name}_enable"

load_rc_config "$name"

: ${centralssh_enable:="NO"}
: ${centralssh_user:="root"}
: ${centralssh_group:="wheel"}
: ${centralssh_config:="/etc/centralssh/config.json"}
: ${centralssh_servers:="/etc/centralssh/servers.json"}
: ${centralssh_known_hosts:="/etc/centralssh/known_hosts"}
: ${centralssh_user_key_root:="/etc/centralssh/users"}
: ${centralssh_audit_log:="/var/log/centralssh/audit.jsonl"}
: ${centralssh_listen:="0.0.0.0:7788"}

pidfile="/var/run/${name}.pid"
procname="/usr/local/sbin/centralssh"
command="/usr/sbin/daemon"
command_args="-p ${pidfile} -u ${centralssh_user} ${procname} --listen ${centralssh_listen} --config ${centralssh_config} --servers ${centralssh_servers} --known-hosts ${centralssh_known_hosts} --user-key-root ${centralssh_user_key_root} --audit-log ${centralssh_audit_log}"

required_files="${centralssh_config} ${centralssh_servers} ${centralssh_known_hosts}"

run_rc_command "$1"
